# MAKEFILE
# Author: Kuziwa Sachikonye
# File Description: Assembly Machine Code Compiler
# Date: Friday 25 August 2015

main.elf:
	arm-none-eabi-as -g -mcpu=cortex-m0 -mthumb -g -o main.o main.s
	arm-none-eabi-ld -Ttext 0x08000000 -o main.elf main.o

clean:
	-rm *.o
	-rm *.elf

debug:
	open -a Terminal "`pwd`" | openocd -f interface/stlink-v2.cfg -f target/stm32f0x_stlink.cfg
	
run:
	make clean
	make
	clear
	arm-none-eabi-gdb main.elf


#Copyright 2015, Kuziwa Sachikonye, All rights reserved.
